# This workfow shows how to build a Docker image, tag and push it to DigitalOcean Container Registry, and
# deploy the application on a DIgitalOcean Kubernetes cluster. For description to the entire worklow, 
# see www.digitalocean.com/docs/kubernetes/how-to/deploy-using-github-actions.

name: Build relay

# Controls when the action will run.
on: workflow_dispatch

# A workflow run is made up of one or more jobs that can run sequentially or in parallel.
jobs:
  # This workflow contains a single job called "build".
  build:
    # The type of runner that the job will run on.
    runs-on: ubuntu-latest
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it.
    - name: Checkout master
      uses: actions/checkout@main
    
    # Build docker
    # To use this Github action file with another part of this repo, or with another project, change the DOCKERFILE and PACKAGE_NAME variables below.
    - name: Build and Push
      run: |
        export DOCKERFILE="./cmd/bigsky/Dockerfile"
        export PACKAGE_NAME="bigsky"
        export REPO_NAME=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
        export TAG=$(echo $GITHUB_SHA | head -c7)
        export IMAGE_NAME="ghcr.io/$REPO_NAME/$PACKAGE_NAME:$TAG"

        docker build -t $IMAGE_NAME -f $DOCKERFILE .
        echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
        echo what docker tag $REPO_NAME/$PACKAGE_NAME$TAG $REPO_NAME/$PACKAGE_NAME:latest
        docker tag $IMAGE_NAME ghcr.io/$REPO_NAME/$PACKAGE_NAME:latest
        docker push $IMAGE_NAME